export * from './types'
export {
  authApi,
  inventoryApi,
  operationsApi,
  mediaApi,
  settingsApi,
  excelApi,
  detailApi,
  printApi,
  healthApi,
  photoRelayApi,
  auditApi,
} from './endpoints'

import {
  inventoryApi,
  operationsApi,
  mediaApi,
  settingsApi,
  excelApi,
  detailApi,
  printApi,
  healthApi,
  photoRelayApi,
  auditApi,
} from './endpoints'

/** 兼容旧代码的统一入口 */
export const api = {
  health: healthApi.check,
  stats: inventoryApi.stats,
  prefixStats: inventoryApi.prefixStats,
  listBracelets: inventoryApi.list,
  getByCert: inventoryApi.getByCert,
  getByCertDbOnly: (certNo: string) => inventoryApi.getByCert(certNo, { dbOnly: true }),
  updateBracelet: inventoryApi.updateByCert,
  deleteBracelet: inventoryApi.deleteByCert,
  outbound: operationsApi.outbound,
  inbound: operationsApi.inbound,
  createNew: operationsApi.createNew,
  registerBracelet: operationsApi.register,
  excelRowPreview: operationsApi.excelRow,
  nextCertNo: operationsApi.nextCertNo,
  revert: operationsApi.revert,
  excelSnapshot: operationsApi.excelSnapshot,
  uploadMedia: mediaApi.upload,
  deleteMedia: mediaApi.delete,
  getSettings: settingsApi.get,
  saveSettings: settingsApi.save,
  getStatus: settingsApi.status,
  restartPrintAgent: settingsApi.restartPrintAgent,
  getLabelTemplate: settingsApi.labelTemplate.get,
  saveLabelTemplate: settingsApi.labelTemplate.save,
  exportExcel: excelApi.export,
  importExcel: excelApi.import,
  excelCertIndexStatus: excelApi.certIndexStatus,
  refreshCertIndex: excelApi.refreshCertIndex,
  searchCertIndex: excelApi.searchCertIndex,
  getDetail: detailApi.get,
  saveDetail: detailApi.save,
  printBraceletTag: printApi.braceletTag,
  createPhotoRelaySession: photoRelayApi.create,
  getPhotoRelayStation: photoRelayApi.station,
  getPhotoRelayMobileInfo: photoRelayApi.mobileInfo,
  syncPhotoRelayCert: photoRelayApi.syncCert,
  pollPhotoRelay: photoRelayApi.poll,
  heartbeatPhotoRelay: photoRelayApi.heartbeat,
  pushPhotoRelayFrame: photoRelayApi.pushFrame,
  shootPhotoRelay: photoRelayApi.shoot,
  getPhotoRelaySession: photoRelayApi.get,
}
